services:
  backend:
    build: ./Backend
    ports:
      - "8000:80"
    volumes:
      - ./Backend/app:/code/app
    networks:
      - project_net
    restart: unless-stopped
  
networks:
  project_net:

